# A docker-compose file that runs commands out of a known image

version: "2"

services:
  aws:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    image: tim77/limbo-test
    entrypoint: [ "/usr/local/bin/aws" ]

  ecs-cli:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      IMAGE_THIS_BUILD:
      SLACK_TOKEN:
      LIMBO_NEEDMENTION:
      LIMBO_CLOUDWATCH:
      SERVICE_NAME:
    image: tim77/limbo-test
    entrypoint: /usr/local/bin/ecs-cli
